version: 0.2
phases:
    install:
        runtime-version:
            nodejs: 12
        commands:
            - npm install
    build:
        commands:
            - npm run-script build
    post_build:
         commands:
            - aws s3 cp build s3://output-teste --recursive =acl public-read
artifacts:
    files:
        - '**/*'
    base-directory: 'build*'
    discard-paths: yes